// Sponsor stakes = unitholding as of Mar 2026 (workbook). REIT structure specs — recreated from the "REIT Structure" PDFs / annual reports (Bagmane from RHP).
// Rendered natively as HTML/SVG by the dashboard; no PDF embeds.
window.REIT_STRUCTURES = {
 embassy: {
  sponsors: [{name:'Blackstone Group', exited:'Dec 2023', exit_note:'sold entire 23.5% (~₹7,100 cr block deal, 20 Dec 2023)'}, {name:'Embassy Group', stake:'8%'}], public_stake:'~92%',
  trustee: 'Axis Trustee Services Ltd',
  manager: 'Embassy Office Parks Management Services Pvt Ltd (EOPMSPL)',
  notes: 'MPPL holds 80% of Embassy Energy (REIT 20% direct). GLSP is a 50:50 JV.',
  spvs: [
   {name:'Manyata Promoters Pvt Ltd (MPPL)', stake:100, assets:['Embassy Manyata']},
   {name:'Vikas Telecom Pvt Ltd / Sarla Infra', stake:100, assets:['Embassy TechVillage']},
   {name:'GolfLinks Software Park Pvt Ltd (GLSP)', stake:50, assets:['Embassy GolfLinks (incl. Pinehurst)']},
   {name:'Quadron Business Park Pvt Ltd', stake:100, assets:['Embassy Quadron','Embassy One & Four Seasons']},
   {name:'Embassy Construction Pvt Ltd', stake:100, assets:['Embassy Business Hub']},
   {name:'Indian Express Newspapers (Mumbai) Pvt Ltd', stake:100, assets:['Express Towers']},
   {name:'Vikhroli Corporate Park Pvt Ltd', stake:100, assets:['Embassy 247']},
   {name:'Earnest Towers Pvt Ltd', stake:100, assets:['First International Financial Centre (FIFC)']},
   {name:'Embassy Pune TechZone Pvt Ltd', stake:100, assets:['Embassy TechZone']},
   {name:'Qubix Business Park Pvt Ltd', stake:100, assets:['Embassy Qubix']},
   {name:'Oxygen Business Park Pvt Ltd', stake:100, assets:['Embassy Oxygen']},
   {name:'Galaxy Square Pvt Ltd', stake:100, assets:['Embassy Galaxy']},
   {name:'ESNP Property Builders & Developers Pvt Ltd', stake:100, assets:['Embassy Splendid TechZone']},
   {name:'Umbel Properties Pvt Ltd', stake:100, assets:['Hilton at Embassy GolfLinks']},
   {name:'Embassy Energy Pvt Ltd (EEPL)', stake:20, via:'MPPL 80%', assets:['Embassy Energy (Solar Park)']},
  ]},
 mindspace: {
  sponsors: [{name:'K Raheja Corp (backed by Blackstone)', stake:'67%'}], public_stake:'~33%',
  trustee: 'Axis Trustee Services Ltd',
  manager: 'K Raheja Corp Investment Managers Pvt Ltd',
  notes: '11% in the three Madhapur SPVs is held by TSIIC (Telangana State). Mack Soft Tech is held via Horizonview Properties (holdco).',
  spvs: [
   {name:'Sundew Properties Ltd', stake:89, assets:['Mindspace Madhapur (Sundew)']},
   {name:'K. Raheja IT Park (Hyderabad) Ltd (KRIT)', stake:89, assets:['Mindspace Madhapur (KRIT)']},
   {name:'Intime Properties Ltd', stake:89, assets:['Mindspace Madhapur (Intime)']},
   {name:'Mindspace Business Parks Pvt Ltd (MBPPL)', stake:100, assets:['Mindspace Airoli West','Mindspace Pocharam','The Square Nagar Road','Commerzone Yerwada','Commerzone Porur']},
   {name:'Gigaplex Estates Pvt Ltd', stake:100, assets:['Mindspace Airoli East']},
   {name:'Avacado Properties & Trading (India) Pvt Ltd', stake:100, assets:['Paradigm Mindspace Malad','The Square BKC']},
   {name:'KRC Infrastructure & Projects Pvt Ltd', stake:100, assets:['Gera Commerzone Kharadi','Pune IT Building Kalyani Nagar']},
   {name:'Sustain Properties Pvt Ltd', stake:100, assets:['Commerzone Raidurg']},
   {name:'Horizonview Properties Pvt Ltd → Mack Soft Tech Pvt Ltd', stake:100, via:'holdco chain', assets:['The Square, 110 Financial District']},
   {name:'Other (Worli / Avenue 98 entities)', stake:100, assets:['The Square / Ascent Worli','The Square Avenue 98']},
  ]},
 brookfield: {
  sponsors: [{name:'Brookfield Asset Management', stake:'19%'}], public_stake:'~81%',
  trustee: 'Axis Trustee Services Ltd',
  manager: 'Brookprop Management Services Pvt Ltd',
  notes: '50% JVs with GIC (Kairos & Candor Gurgaon One). Rostrum Realty (50%, Bharti JV) is the North Commercial Portfolio holding entity. Candor India Office Parks is the operational service provider.',
  spvs: [
   {name:'Candor Kolkata One Hi-Tech Structures Pvt Ltd', stake:100, assets:['Candor TechSpace G2 (Gurugram)','Candor TechSpace K1 (Kolkata)']},
   {name:'Shantiniketan Properties Pvt Ltd', stake:100, assets:['Candor TechSpace N1 (Noida)']},
   {name:'Seaview Developers Pvt Ltd', stake:100, assets:['Candor TechSpace N2 (Noida)']},
   {name:'Festus Properties Pvt Ltd', stake:100, assets:['Kensington / Downtown Powai SEZ (Mumbai)']},
   {name:'Ariiga Ecoworld Business Parks Pvt Ltd', stake:100, assets:['Ecoworld (Bengaluru)']},
   {name:'Kairos Properties Pvt Ltd', stake:50, via:'GIC 50%', assets:['Downtown Powai — Commercial/IT (Mumbai)']},
   {name:'Candor Gurgaon One Realty Projects Pvt Ltd', stake:50, via:'GIC 50%', assets:['Candor TechSpace G1 (Gurugram)']},
   {name:'Rostrum Realty Pvt Ltd (holding co)', stake:50, via:'Bharti 50%', assets:['Airtel Center (Gurugram)','Pavilion Mall (Ludhiana)']},
   {name:'Aspen Buildtech Pvt Ltd', stake:50, via:'via Rostrum', assets:['Worldmark 1 (New Delhi)']},
   {name:'Oak Infrastructure Developers Pvt Ltd', stake:50, via:'via Rostrum', assets:['Worldmark 2 & 3 (New Delhi)']},
   {name:'Arnon Builders & Developers Pvt Ltd', stake:50, via:'via Rostrum', assets:['Worldmark Gurugram']},
  ]},
 nexus: {
  sponsors: [{name:'Blackstone (Sponsor Group)', stake:'22%'}], public_stake:'~78%',
  trustee: 'Axis Trustee Services Ltd',
  manager: 'Nexus Select Mall Management Pvt Ltd',
  notes: 'Trust holds most SPVs ~100% (99.45% in select cases). ITIPL (Treasure Island) is 50:50 with a JV partner. NSRPL entitled to 64.9% of the economic interest from Nexus Shantiniketan per SAA.',
  spvs: [
   {name:'SIPL', stake:100, assets:['Nexus Select Citywalk (Delhi)','Nexus Seawoods (Navi Mumbai)','Nexus MBD (Ludhiana)']},
   {name:'CSJIPL', stake:100, assets:['Nexus Elante Complex (Chandigarh)']},
   {name:'EDPL', stake:100, assets:['Nexus Amritsar','Nexus Ahmedabad One']},
   {name:'NHRPL', stake:100, assets:['Nexus Koramangala (Bengaluru)','Nexus Hyderabad']},
   {name:'NNMCPL', stake:100, assets:['Nexus Indore Central']},
   {name:'SRPL', stake:100, assets:['Nexus Esplanade (Bhubaneswar)']},
   {name:'NWPL', stake:100, assets:['Nexus Whitefield Complex (Bengaluru)']},
   {name:'CPPL', stake:100, assets:['Nexus Westend Complex (Pune)']},
   {name:'DIPL', stake:100, assets:['Westend Icon Offices (Pune)']},
   {name:'NMRPL (Mysuru)', stake:100, assets:['Nexus Centre City (Mysuru)']},
   {name:'NMRPL (Mangaluru)', stake:100, assets:['Fiza by Nexus (Mangaluru)']},
   {name:'NSRPL', stake:100, assets:['Nexus Shantiniketan (Bengaluru)']},
   {name:'NJRPL', stake:100, assets:['Nexus Celebration (Udaipur)']},
   {name:'VPPL', stake:100, assets:['Nexus Vijaya Complex (Chennai)','Nexus Vega City (Bengaluru)']},
   {name:'MSPL', stake:100, assets:['Karnataka Solar Park']},
   {name:'ITIPL', stake:50, via:'JV partner 50%', assets:['Treasure Island (Indore)']},
  ]},
 krt: {
  sponsors: [{name:'Sattva Group', stake:'32%'}, {name:'Blackstone (Sponsor Group)', stake:'47%'}], public_stake:'~21%',
  trustee: 'Axis Trustee Services Ltd',
  manager: 'Knowledge Realty Office Management Services Pvt Ltd (KROMSPL)',
  notes: 'Simplified view — KRT holds 30+ SPVs/holdcos, largely 100% (a few via holding companies and CAM entities). See annual report FY2025-26 pp. 38-39 for the full chart.',
  spvs: [
   {name:'Hyderabad cluster SPVs', stake:100, assets:['Sattva Knowledge City','Sattva Knowledge Park','Sattva Knowledge Capital','One Qube','Sattva Knowledge Court','Sattva Image Tower']},
   {name:'Mumbai cluster SPVs', stake:100, assets:['One BKC','One World Center','One International Center','One Unity Center','Prima Bay']},
   {name:'Bengaluru cluster SPVs', stake:100, assets:['Cessna Business Park','Exora Business Park','Sattva Softzone','Sattva Global City','Sattva Horizon','Sattva Touchstone','Sattva Cosmo Lavelle','Sattva Endeavour','and more']},
   {name:'Chennai / Pune / GIFT SPVs', stake:100, assets:['One Trade Tower','Kosmo One','Fintech One','Sattva Premia','One Paramount (Techpoint)']},
   {name:'Solar SPVs', stake:100, assets:['One BKC Solar','Prima Bay Solar','Karnataka Solar I & II']},
  ]},
 bagmane: {
  sponsors: [{name:'Bagmane Group (backed by CPP Investments)', stake:'83%'}], public_stake:'~17%',
  trustee: 'Axis Trustee Services Ltd',
  manager: 'Bagmane Realty Investment Manager Pvt Ltd',
  notes: 'From the RHP (May 2026 IPO). Portfolio companies acquired by the Trust at IPO completion.',
  spvs: [
   {name:'Bagmane Developers Pvt Ltd & portfolio companies', stake:100, assets:['Bagmane World Technology Centre','Bagmane Constellation Business Park','Bagmane Rio Business Park','Luxor @ Bagmane Capital','Bagmane Tech Park','Bagmane Cosmos Business Park','UC Hotels @ BWTC','Solar assets (Karnataka)']},
  ]},
};
